### ISSUE TITLE
Git repo too big

### ISSUE THREAD

**Issue by cristim** [djhenry/selenium-webdriver-rpm#2]
Please clean up the repo history(or re-create it fresh), the previous commits that had binaries checked in are making it huge and quite slow to clone.

**Comment by cristim** [comment]
I managed to delete the binaries from the history, bumped the version to the latest and added a Makefile for easier installation. You can see these changes in my fork: https://github.com/cristim/selenium-webdriver-rpm

**Comment by djhenry** [comment]
Thanks for the update!  It has been difficult to find time to work on
this.  I made a force push of your change which has brought the repo back
down to a reasonable size.
